In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 한글 설정
import matplotlib as mpl
mpl.rc('font', family='AppleGothic')
plt.rcParams['axes.unicode_minus'] = False

# import matplotlib.font_manager as fm
# font_name = fm.FontProperties(fname="/Users/dofany/dofany_study/python/analysis/data/ImcreSoojin OTF.otf").get_name()
# plt.rc("font", family=font_name)

import seaborn as sns

plt.style.use("fivethirtyeight")

import warnings
warnings.filterwarnings("ignore")

# 서울시 구별 범죄 현황 분석

## 데이터 준비

+ https://www.data.go.kr
+ 구글에서 "서울시 관서별 5대 범죄 발생검거 현황" 검색
+ 부제
    - cctv와 범죄, 검거율에 관계가 있는가?
    - 강남 3구는 과연 범죄, 검거율이 높은가?

In [98]:
crime = pd.read_csv("data/crime_in_seoul.csv",encoding="EUC-KR",thousands=',')
crime.head()

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
0   중부서      2      2      3      2    105     65   1395    477   1355   1170
1   종로서      3      3      6      5    115     98   1070    413   1278   1070
2  남대문서      1      0      6      4     65     46   1153    382    869    794
3  서대문서      2      2      5      4    154    124   1812    738   2056   1711
4   혜화서      3      2      5      4     96     63   1114    424   1015    861

In [99]:
crime.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   관서명     31 non-null     object
 1   살인 발생   31 non-null     int64
 2   살인 검거   31 non-null     int64
 3   강도 발생   31 non-null     int64
 4   강도 검거   31 non-null     int64
 5   강간 발생   31 non-null     int64
 6   강간 검거   31 non-null     int64
 7   절도 발생   31 non-null     int64
 8   절도 검거   31 non-null     int64
 9   폭력 발생   31 non-null     int64
 10  폭력 검거   31 non-null     int64
dtypes: int64(10), object(1)
memory usage: 2.8+ KB

# EDA & Preprocessing

## 관서명을 구 이름으로 변경

+ https://ko.wikipedia.org/wiki/서울특별시지방경찰청


+ GoogleMap API를 이용하여 주소 획득
    - https://developers.google.com
    - pip install googlemaps

In [100]:
import googlemaps

In [10]:
g_key = "AIzaSyC7dlYwoG75UJ0zisujCoTMyTsppcqpnY0"
gmap = googlemaps.Client(key=g_key)
gmap

In [ ]:
'''
['대한민국 서울특별시 중구 을지로동 수표로 27', '대한민국 서울특별시 종로구 종로1.2.3.4가동 율곡로 46', '대한민국 서울특별시 중구 회현동 한강대로 410', '대한민국 서울특별시 서대문구 충현동 통일로 113', '대한민국 서울특별시 종로구 인의동 창경궁로 112-16', '대한민국 서울특별시 용산구 원효로1가 백범로 329', '대한민국 서울특별시 성북구 삼선동5가 301', '대한민국 서울특별시 동대문구 청량리동 약령시로21길 29', '대한민국 서울특별시 마포구 아현동 마포대로 183', '대한민국 서울특별시 영등포구 영등포동1가 618-7', '대한민국 서울특별시 성동구 행당동 왕십리광장로 9', '대한민국 서울특별시 동작구 노량진1동 노량진로 148', '대한민국 서울특별시 광진구 구의동 자양로 167', '대한민국 서울특별시 은평구 녹번동 진흥로 58', '대한민국 서울특별시 강북구 번1동 오패산로 406', '대한민국 서울특별시 금천구 시흥1동 시흥대로73길 50', '대한민국 서울특별시 중랑구 신내동 신내역로3길 40-10', '대한민국 서울특별시 강남구 대치동 998', '대한민국 서울특별시 관악구 봉천동', '대한민국 서울특별시 양천구 신월동 화곡로 73', '대한민국 서울특별시 강동구 성내1동 성내로 57', '대한민국 서울특별시 성북구 종암동 종암로 135', '대한민국 서울특별시 구로구 구로동 가마산로 235', '대한민국 서울특별시 서초구 서초3동 반포대로 179', '대한민국 서울특별시 양천구 신정6동 목동동로 99', '대한민국 서울특별시 송파구 가락동 중대로 221', '대한민국 서울특별시 노원구 하계동 노원로 283', '대한민국 서울특별시 서초구 방배본동 동작대로 204', '대한민국 서울특별시 은평구 불광동 연서로 365', '대한민국 서울특별시 도봉구 창4동 노해로 403', '대한민국 서울특별시 강남구 개포동 개포로 617']
[37.5636465, 37.5755578, 37.5547584, 37.5647439, 37.5718529, 37.5387099, 37.5897482, 37.58506149999999, 37.550814, 37.5153176, 37.5617303, 37.5130866, 37.542873, 37.6020914, 37.63730390000001, 37.4568722, 37.6186095, 37.5094352, 37.4743789, 37.5397827, 37.528511, 37.6020592, 37.494931, 37.4956054, 37.5165667, 37.5016941, 37.6425238, 37.4945959, 37.6283597, 37.6533589, 37.49349]
[126.9895796, 126.9848674, 126.9734981, 126.9667705, 126.9989143, 126.9659183, 127.0161353, 127.0457679, 126.954028, 126.905728, 127.0364217, 126.9428498, 127.083821, 126.9213528, 127.0273399, 126.8970429, 127.1045734, 127.0669578, 126.9509748, 126.8299968, 127.1268224, 127.0321577, 126.886731, 127.0052504, 126.8656763, 127.1272481, 127.0717076, 126.9831279, 126.9287226, 127.052682, 127.0772119]
'''
# 주소
# 위도
# 경도

In [101]:
station_address = ['대한민국 서울특별시 중구 을지로동 수표로 27', '대한민국 서울특별시 종로구 종로1.2.3.4가동 율곡로 46', '대한민국 서울특별시 중구 회현동 한강대로 410', '대한민국 서울특별시 서대문구 충현동 통일로 113', '대한민국 서울특별시 종로구 인의동 창경궁로 112-16', '대한민국 서울특별시 용산구 원효로1가 백범로 329', '대한민국 서울특별시 성북구 삼선동5가 301', '대한민국 서울특별시 동대문구 청량리동 약령시로21길 29', '대한민국 서울특별시 마포구 아현동 마포대로 183', '대한민국 서울특별시 영등포구 영등포동1가 618-7', '대한민국 서울특별시 성동구 행당동 왕십리광장로 9', '대한민국 서울특별시 동작구 노량진1동 노량진로 148', '대한민국 서울특별시 광진구 구의동 자양로 167', '대한민국 서울특별시 은평구 녹번동 진흥로 58', '대한민국 서울특별시 강북구 번1동 오패산로 406', '대한민국 서울특별시 금천구 시흥1동 시흥대로73길 50', '대한민국 서울특별시 중랑구 신내동 신내역로3길 40-10', '대한민국 서울특별시 강남구 대치동 998', '대한민국 서울특별시 관악구 봉천동', '대한민국 서울특별시 양천구 신월동 화곡로 73', '대한민국 서울특별시 강동구 성내1동 성내로 57', '대한민국 서울특별시 성북구 종암동 종암로 135', '대한민국 서울특별시 구로구 구로동 가마산로 235', '대한민국 서울특별시 서초구 서초3동 반포대로 179', '대한민국 서울특별시 양천구 신정6동 목동동로 99', '대한민국 서울특별시 송파구 가락동 중대로 221', '대한민국 서울특별시 노원구 하계동 노원로 283', '대한민국 서울특별시 서초구 방배본동 동작대로 204', '대한민국 서울특별시 은평구 불광동 연서로 365', '대한민국 서울특별시 도봉구 창4동 노해로 403', '대한민국 서울특별시 강남구 개포동 개포로 617']
station_lat = [37.5636465, 37.5755578, 37.5547584, 37.5647439, 37.5718529, 37.5387099, 37.5897482, 37.58506149999999, 37.550814, 37.5153176, 37.5617303, 37.5130866, 37.542873, 37.6020914, 37.63730390000001, 37.4568722, 37.6186095, 37.5094352, 37.4743789, 37.5397827, 37.528511, 37.6020592, 37.494931, 37.4956054, 37.5165667, 37.5016941, 37.6425238, 37.4945959, 37.6283597, 37.6533589, 37.49349]
station_lng = [126.9895796, 126.9848674, 126.9734981, 126.9667705, 126.9989143, 126.9659183, 127.0161353, 127.0457679, 126.954028, 126.905728, 127.0364217, 126.9428498, 127.083821, 126.9213528, 127.0273399, 126.8970429, 127.1045734, 127.0669578, 126.9509748, 126.8299968, 127.1268224, 127.0321577, 126.886731, 127.0052504, 126.8656763, 127.1272481, 127.0717076, 126.9831279, 126.9287226, 127.052682, 127.0772119]

In [103]:
### 받은 주소에서 구 이름만 추출
add = pd.DataFrame([station_address,station_lat,station_lng]).T
add.columns = ['구별','위도','경도']
add['구별'] = add['구별'].str.split(' ',expand=True)[2]
add['구별'].head()

0      중구
1     종로구
2      중구
3    서대문구
4     종로구
Name: 구별, dtype: object

In [104]:
import re
lst = list()
for i in range(len(station_address)):
    a = re.search("[가-힣]+구", station_address[i]).group()
    lst.append(a)
    
pd.DataFrame(lst).head()

      0
0    중구
1   종로구
2    중구
3  서대문구
4   종로구

In [108]:
gu_names =[] 

for name in station_address: 
    tmp = name.split()
    
    tmp_gu = [gu for gu in tmp if gu[-1] == "구"][0]
    gu_names.append(tmp_gu)
    
print(gu_names)

['중구', '종로구', '중구', '서대문구', '종로구', '용산구', '성북구', '동대문구', '마포구', '영등포구', '성동구', '동작구', '광진구', '은평구', '강북구', '금천구', '중랑구', '강남구', '관악구', '양천구', '강동구', '성북구', '구로구', '서초구', '양천구', '송파구', '노원구', '서초구', '은평구', '도봉구', '강남구']

In [109]:
### 테이블에 "구별" 컬럼 추가
crime['구별'] = gu_names
crime

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구
5,용산서,5,5,14,14,194,173,1557,587,2050,1704,용산구
6,성북서,2,2,2,1,86,71,953,409,1194,1015,성북구
7,동대문서,5,5,13,13,173,146,1981,814,2548,2227,동대문구
8,마포서,8,8,14,10,294,247,2555,813,2983,2519,마포구
9,영등포서,14,12,22,20,295,183,2964,978,3572,2961,영등포구
10,성동서,4,4,9,8,126,119,1607,597,1612,1395,성동구
11,동작서,5,5,9,5,285,139,1865,661,1910,1587,동작구
12,광진서,4,4,14,26,240,220,3026,1277,2625,2180,광진구
13,서부서,2,2,2,1,70,59,819,293,1192,1038,은평구
14,강북서,7,8,14,13,153,126,1434,618,2649,2348,강북구
15,금천서,3,4,6,6,151,122,1567,888,2054,1776,금천구
16,중랑서,13,12,11,9,187,148,2135,829,2847,2407,중랑구
17,강남서,3,3,15,12,300,225,2411,984,2465,2146,강남구
18,관악서,9,8,12,14,320,221,2706,827,3298,2642,관악구
19,강서서,7,8,13,13,262,191,2096,1260,3207,2718,양천구
20,강동서,4,3,6,8,156,123,2366,789,2712,2248,강동구
21,종암서,3,3,3,3,64,53,832,332,1015,840,성북구
22,구로서,8,6,15,11,281,164,2335,889,3007,2432,구로구
23,서초서,7,4,8,5,334,193,1982,905,1852,1607,서초구
24,양천서,3,5,6,3,120,105,1890,672,2509,2030,양천구
25,송파서,11,10,13,10,220,178,3239,1129,3295,2786,송파구
26,노원서,10,10,7,7,197,121,2193,801,2723,2329,노원구
27,방배서,1,2,1,1,59,56,653,186,547,491,서초구
28,은평서,1,1,7,5,96,82,1095,418,1461,1268,은평구
29,도봉서,3,3,9,10,102,106,1063,478,1487,1303,도봉구
30,수서서,10,7,6,6,149,124,1439,666,1819,1559,강남구

In [116]:
#강서경찰서는 강서구로 변경 
crime["구별"][19]="강서구"

#강서경찰서는 강서구로 변경 - 조건식으로 영리하게 바꾸는 법
crime.loc[crime["관서명"]=="강서서",["구별"]]="강서구"
crime

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구
5,용산서,5,5,14,14,194,173,1557,587,2050,1704,용산구
6,성북서,2,2,2,1,86,71,953,409,1194,1015,성북구
7,동대문서,5,5,13,13,173,146,1981,814,2548,2227,동대문구
8,마포서,8,8,14,10,294,247,2555,813,2983,2519,마포구
9,영등포서,14,12,22,20,295,183,2964,978,3572,2961,영등포구
10,성동서,4,4,9,8,126,119,1607,597,1612,1395,성동구
11,동작서,5,5,9,5,285,139,1865,661,1910,1587,동작구
12,광진서,4,4,14,26,240,220,3026,1277,2625,2180,광진구
13,서부서,2,2,2,1,70,59,819,293,1192,1038,은평구
14,강북서,7,8,14,13,153,126,1434,618,2649,2348,강북구
15,금천서,3,4,6,6,151,122,1567,888,2054,1776,금천구
16,중랑서,13,12,11,9,187,148,2135,829,2847,2407,중랑구
17,강남서,3,3,15,12,300,225,2411,984,2465,2146,강남구
18,관악서,9,8,12,14,320,221,2706,827,3298,2642,관악구
19,강서서,7,8,13,13,262,191,2096,1260,3207,2718,강서구
20,강동서,4,3,6,8,156,123,2366,789,2712,2248,강동구
21,종암서,3,3,3,3,64,53,832,332,1015,840,성북구
22,구로서,8,6,15,11,281,164,2335,889,3007,2432,구로구
23,서초서,7,4,8,5,334,193,1982,905,1852,1607,서초구
24,양천서,3,5,6,3,120,105,1890,672,2509,2030,양천구
25,송파서,11,10,13,10,220,178,3239,1129,3295,2786,송파구
26,노원서,10,10,7,7,197,121,2193,801,2723,2329,노원구
27,방배서,1,2,1,1,59,56,653,186,547,491,서초구
28,은평서,1,1,7,5,96,82,1095,418,1461,1268,은평구
29,도봉서,3,3,9,10,102,106,1063,478,1487,1303,도봉구
30,수서서,10,7,6,6,149,124,1439,666,1819,1559,강남구

## checkPoint

In [117]:
crime.to_csv('data/crime_in_seoul_include_gu_name.csv',encoding="utf-8")

In [131]:
### 다시 작업 시작
crime_raw = pd.read_csv("data/crime_in_seoul_include_gu_name.csv", index_col=0)
crime_raw.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

## 관서명을 없애고 구별을 인덱스로 설정

In [136]:
# 관서명 기준이기 때문에 "구별" 값이 중복된다.

crime_anal = pd.pivot_table(crime_raw,index='구별', aggfunc='sum')
crime_anal.head()

     강간 검거  강간 발생  강도 검거  강도 발생  살인 검거  살인 발생  절도 검거  절도 발생  폭력 검거  폭력 발생
구별
강남구    349    449     18     21     10     13   1650   3850   3705   4284
강동구    123    156      8      6      3      4    789   2366   2248   2712
강북구    126    153     13     14      8      7    618   1434   2348   2649
강서구    191    262     13     13      8      7   1260   2096   2718   3207
관악구    221    320     14     12      8      9    827   2706   2642   3298

## 각 범죄별 검거율을 계산하여 파생변수 추가하고, 각 검거 컬럼은 삭제

In [137]:
crime_anal['강간검거율'] = crime_anal['강간 검거'] / crime_anal['강간 발생'] * 100
crime_anal['강도검거율'] = crime_anal['강도 검거'] / crime_anal['강도 발생'] * 100
crime_anal['살인검거율'] = crime_anal['살인 검거'] / crime_anal['살인 발생'] * 100
crime_anal['절도검거율'] = crime_anal['절도 검거'] / crime_anal['절도 발생'] * 100
crime_anal['폭력검거율'] = crime_anal['폭력 검거'] / crime_anal['폭력 발생'] * 100

del crime_anal['강간 검거']
del crime_anal['강도 검거']
del crime_anal['살인 검거']
del crime_anal['절도 검거']
del crime_anal['폭력 검거']

In [138]:
crime_anal.head()

,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
강서구,262,13,7,2096,3207,72.900763,100.000000,114.285714,60.114504,84.752105
관악구,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157

In [140]:
### "발생"이라는 단어는 삭제(컬럼 변경)

crime_anal.rename(columns={"강간 발생":"강간", "강도 발생":"강도", "살인 발생":"살인",
                          "절도 발생":"절도", "폭력 발생":"폭력"}, inplace=True)
crime_anal.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
강서구,262,13,7,2096,3207,72.900763,100.000000,114.285714,60.114504,84.752105
관악구,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157

In [141]:
### 검거율에서 100이 넘는 값들은 모두 100으로 맞춰준다.

for col in ['강간검거율','강도검거율','살인검거율','절도검거율','폭력검거율']:
    crime_anal.loc[crime_anal[col]> 100, col] = 100
    
crime_anal.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
강서구,262,13,7,2096,3207,72.900763,100.000000,100.000000,60.114504,84.752105
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157

## 정규화 / 표준화 : 수치 데이터에 대한 rescaling
+ 정규화(Normalization)
    - 데이터의 상대적인 크기에 대해 영향을 줄이기 위해 데이터 범위를 0~1로 변환
    - (측정값 - 최소값) / (최대값 - 최소값)

+ 표준화(Standardization)
    - 데이터가 평균으로부터 얼마나 떨어져 있는지 나타내는 값으로, 특정 범위를 벗어난 데이터는 이상치로 간주
    - (측정값 - 평균) / 표준편차

In [ ]:
from sklearn import preprocessing
min_max_scaler = preprocessing, MinMaxScaler()